window.BLOG_CATEGORIES = {
  'Recipes': '#B9B842',
  'Behind the Brand': '#B5031F',
  'Wellness': '#C73D50',
  'News': '#884D2F',
};

window.BLOG_POSTS = [
  {
    slug: 'why-we-went-zero-sugar',
    title: 'Why We Went Zero Sugar',
    category: 'Wellness',
    excerpt: 'Most sodas ask you to choose between flavor and your health. We spent a year in the lab making sure Dose of Island never would.',
    author: 'Nadia Perera',
    authorBio: 'Nadia leads product development at Dose of Island and spent six years formulating beverages before going all-in on zero-sugar soda.',
    date: 'July 28, 2026',
    readTime: '4 min read',
    featured: true,
    body: [
      { type: 'paragraph', text: 'When we started testing recipes for Dose of Island, the easy path was obvious: add sugar, and everything tastes better instantly. Most of the soda industry has built itself around that shortcut for a century. We didn\'t want to take it.' },
      { type: 'heading', text: 'The problem with "diet" soda' },
      { type: 'paragraph', text: 'Zero-sugar drinks have a reputation problem. Artificial sweeteners can leave a bitter aftertaste, and a lot of "healthy" sodas taste like an apology for not having sugar in them. We wanted a can that didn\'t taste like a compromise.' },
      { type: 'quote', text: 'We didn\'t want to make a diet soda. We wanted to make a soda that happened to have zero sugar.' },
      { type: 'paragraph', text: 'That meant starting with real fruit instead of flavor syrups, and testing dozens of carbonation levels and fruit ratios until the sweetness came from the fruit itself, balanced by fizz instead of masked by it.' },
      { type: 'image', src: '', caption: 'Early recipe testing at our Colombo kitchen.' },
      { type: 'heading', text: 'What ended up in the can' },
      { type: 'list', items: ['Real fruit juice and puree as the base sweetness', 'Sparkling water for the fizz, not corn syrup', 'Less than 1g of sugar and under 10 calories per can', 'No artificial sweeteners, no preservatives'] },
      { type: 'paragraph', text: 'A year and dozens of failed batches later, we landed on six flavors we were proud to put our name on. Every one of them still starts with a piece of real fruit, not a lab-made flavor compound.' },
    ],
  },
  {
    slug: 'behind-the-label-real-fruit-real-sri-lanka',
    title: 'Behind the Label: Real Fruit, Real Sri Lanka',
    category: 'Behind the Brand',
    excerpt: 'Every can starts with fruit grown close to home. Here\'s how we source pomegranate, passionfruit, and guava without cutting corners.',
    author: 'Kavindu Silva',
    authorBio: 'Kavindu manages sourcing and supplier relationships across Sri Lanka for Dose of Island.',
    date: 'July 14, 2026',
    readTime: '5 min read',
    featured: false,
    body: [
      { type: 'paragraph', text: 'Sri Lanka grows some of the best tropical fruit in the world, and most of it never makes it into a soda can. We wanted to change that, starting with the growers themselves.' },
      { type: 'heading', text: 'Working with small farms' },
      { type: 'paragraph', text: 'Instead of buying flavor concentrate from an overseas supplier, we work directly with small farms across the island for our passionfruit, guava, and pomegranate. It costs more and takes longer, but it means the fruit in your can was picked, not synthesized.' },
      { type: 'image', src: '', caption: 'A passionfruit harvest outside Kandy.' },
      { type: 'quote', text: 'If we can\'t trace a fruit back to a farm, it doesn\'t go in the can.' },
      { type: 'paragraph', text: 'Watermelon and lime are sourced seasonally from the south, while tamarind comes from smallholders in the dry zone who\'ve grown it for generations. Every flavor has a story attached to a specific region of the island.' },
      { type: 'heading', text: 'Why it matters' },
      { type: 'paragraph', text: 'Supporting local agriculture isn\'t just good marketing copy for us &mdash; it\'s the only way to guarantee the fruit is fresh enough to carry real flavor without needing sugar to prop it up.' },
    ],
  },
  {
    slug: 'three-ways-to-mix-dose-of-island',
    title: 'Three Ways to Mix Dose of Island Into Your Next Party',
    category: 'Recipes',
    excerpt: 'Zero sugar doesn\'t mean zero fun. Three easy mixers using cans you probably already have in the fridge.',
    author: 'Dose of Island Team',
    authorBio: 'Recipes, tips, and drink ideas from the team behind Dose of Island.',
    date: 'June 30, 2026',
    readTime: '3 min read',
    featured: false,
    body: [
      { type: 'paragraph', text: 'A can of Dose of Island is great on its own, but it also makes a solid mixer base &mdash; the carbonation and real fruit flavor hold up better than syrupy sodas once you start adding things to it.' },
      { type: 'heading', text: '1. Pomegranate Spritz' },
      { type: 'paragraph', text: 'Pour a can of Pomegranate over ice, add a splash of soda water and a wedge of lime. Garnish with mint if you have it. Done in under a minute.' },
      { type: 'heading', text: '2. Tamarind Ginger Cooler' },
      { type: 'paragraph', text: 'Mix Tamarind with a small amount of ginger syrup and a squeeze of lime. The tang from the tamarind and the bite of ginger balance each other out well over ice.' },
      { type: 'heading', text: '3. Guava Punch (for a crowd)' },
      { type: 'list', items: ['4 cans Guava', '2 cans Passionfruit', 'A handful of mint leaves', 'Sliced guava for garnish'] },
      { type: 'paragraph', text: 'Combine everything in a large pitcher right before serving so the fizz doesn\'t go flat. Scales up easily for a party &mdash; just keep the ratio of guava to passionfruit at 2:1.' },
    ],
  },
  {
    slug: 'meet-the-farmers-behind-our-pomegranate',
    title: 'Meet the Farmers Behind Our Pomegranate',
    category: 'News',
    excerpt: 'A conversation with the family farm in the dry zone that supplies the pomegranate in every can.',
    author: 'Kavindu Silva',
    authorBio: 'Kavindu manages sourcing and supplier relationships across Sri Lanka for Dose of Island.',
    date: 'June 9, 2026',
    readTime: '4 min read',
    featured: false,
    body: [
      { type: 'paragraph', text: 'We spent a morning at the farm that supplies our pomegranate, a three-generation operation that\'s been growing fruit in the dry zone since long before Dose of Island existed.' },
      { type: 'image', src: '', caption: 'The Fernando family orchard.' },
      { type: 'paragraph', text: 'What struck us most was how much they cared about where the fruit ended up. They wanted to know it wasn\'t going to sit in a warehouse as concentrate for months &mdash; that it would be pressed and in a can within days of harvest.' },
      { type: 'quote', text: 'We\'ve grown pomegranate for thirty years. We just never had anyone ask us how before.' },
      { type: 'paragraph', text: 'That partnership is now in its second year, and it\'s the reason our Pomegranate flavor tastes different from what you\'d get out of a syrup bottle &mdash; it\'s the same fruit you\'d find at a market, just carbonated.' },
    ],
  },
];
